# Site settings
name: Hemchander S
title: Hemchander S | Senior Developer Advocate, Freshworks
description: Hemchander is from the Developer Relations team at Freshworks and is actively involved in building a vibrant developer ecosystem. He loves writing code, making tutorials, giving talks and eating nachos. Location - Freshworks Chennai,India
url: https://he.ms/
baseurl: ""
email: mail@he.ms
cover: 
logo: https://he.ms/img/emojis/technologist.png
resume: Hem-Resume.pdf
social:
  - title: twitter
    url: https://twitter.com/HemSays
  - title: linkedin
    url: https://www.linkedin.com/in/hems23/
  - title: github
    url: https://github.com/hemchander23   
  - title: instagram
    url: https://www.instagram.com/im.he.ms/



# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
